name = "C3D"
uuid = "de436766-0b2a-5f82-bc5b-1ccc5f599b83"
authors = ["Allen Hill <allenofthehills@gmail.com>"]
version = "0.5.2"

[compat]
julia = "1"

[deps]
VaxData = "a6f58a78-e649-57e2-81bc-1d865c7b74f7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
